menu:
    博客: /
    微博: http://weibo.com/2451315930
    rss: /atom.xml
    github: https://github.com/sodatea

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
ga:
# baidu-analytics:
ba:

node_sass:
    outputStyle: compressed

# If you do not need to display math formulas on the blog, disabling MathJax will improve the load time a little bit
disable_mathjax: false

# Use [USTC's Google Fonts Mirror](https://lug.ustc.edu.cn/wiki/lug/services/googlefonts), for Chinese users
use_ustc_mirror: true

# It's recommended to use reverse proxy for duoshuo avatars, so as to support ssl.
# In that way, you need to serve a modified version of the embed.js file.
# Then you can serve that file in any server/cdn and put its address here.
# https://quericy.me/blog/788
# https://imququ.com/post/duoshuo-and-https.html
duoshuo_embed_url:
