menu:
    博客: /
    微博: http://weibo.com/2451315930
    rss: /atom.xml
    github: https://github.com/sodatea

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics tracking id:
ga:
# baidu-analytics:
ba:

node_sass:
    outputStyle: compressed

# If you do not need to display math formulas on the blog, disabling MathJax will improve the load time a little bit
disable_mathjax: false

# For Chinese users, it's necessary to use a mirror for google fonts
# There're 3 recommended mirrors which support SSL:
# 1. USTC: https://fonts.lug.ustc.edu.cn
# 2. css.net: https://cdn.css.net/fonts/
# 3. Baomitu: https://cdn.baomitu.com/index/fonts
#
# Update: Google Fonts has been unblocked in China since 2016
# google_fonts_mirror: fonts.lug.ustc.edu.cn

# It's recommended to use reverse proxy for duoshuo avatars, so as to support ssl.
# In that way, you need to serve a modified version of the embed.js file.
# Then you can serve that file in any server/cdn and put its address here.
# https://quericy.me/blog/788
# https://imququ.com/post/duoshuo-and-https.html
duoshuo_embed_url:

archive_generator:
    per_page: 0

enforce_ssl_on_domains:
    - 'sodatea.github.io'
